---
# tasks file for vault_k8s


- name: Создать Namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ vault_namespace }}"

- name: Создать ServiceAccount для приложения
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    namespace: "{{ vault_namespace }}"
    definition: "{{ lookup('template', 'templates/vault-service-account.yaml.j2') | from_yaml }}"


- name: Создать Role для Vault Auth
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    namespace: "{{ vault_namespace }}"
    definition: "{{ lookup('template', 'templates/vault-role.yaml.j2') | from_yaml }}"

- name: Создать RoleBinding для Vault Auth
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    namespace: "{{ vault_namespace }}"
    definition: "{{ lookup('template', 'templates/vault-rolebinding.yaml.j2') | from_yaml }}"



- name: Создать ConfigMap
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    namespace: "{{ vault_namespace }}"
    definition: "{{ lookup('template', 'templates/vault-config.yaml.j2') | from_yaml }}"



- name: Создать StatefulSet
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"  
    state: present
    namespace: "{{ vault_namespace }}"
    definition: "{{ lookup('template', 'templates/vault-statefulset.yaml.j2') | from_yaml }}"

- name: Создать Service
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    namespace: "{{ vault_namespace }}"
    definition: "{{ lookup('template', 'templates/vault-service.yaml.j2') | from_yaml }}"


- name: Создать Ingress
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    namespace: "{{ vault_namespace }}"
    definition: "{{ lookup('template', 'templates/vault_ingress.yaml.j2') | from_yaml }}"

