---
# tasks file for k8s_apply_deployment

- name: Install Kubernetes Ansible collection
  ansible.builtin.ansible.builtin.ansible-galaxy:
    name: kubernetes.core
    type: collection
    state: latest

- name: Ensure namespace exists
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ namespace }}"

- name: Apply Kubernetes pod
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition: "{{ lookup('template', 'pod.yml.j2') }}"
